// Generated by LiveScript 1.4.0
(function(){
  var Entity;
  module.exports = Entity = (function(){
    Entity.displayName = 'Entity';
    var prototype = Entity.prototype, constructor = Entity;
    function Entity(game){
      var renderer;
      this.game = game;
      this.id = this.game.nextEntityId++;
      this.game.entities[this.id] = this;
      this.pos = [0, 0];
      this.size = [0, 0];
      this.solid = false;
      this.sprite = null;
      this.color = [1, 1, 1, 1];
      renderer = null;
      Object.defineProperty(this, 'renderer', {
        get: function(){
          return renderer;
        },
        set: function(value){
          if (renderer === value) {
            return;
          }
          if (value != null) {
            if (renderer == null) {
              this.game.entitiesRenderable[this.id] = this;
            }
          } else if (renderer != null) {
            delete this.game.entitiesRenderable[this.id];
          }
          return renderer = value;
        }
      });
    }
    return Entity;
  }());
}).call(this);
