// Generated by LiveScript 1.4.0
(function(){
  var SpriteRenderer, out$ = typeof exports != 'undefined' && exports || this;
  out$.SpriteRenderer = SpriteRenderer = require("./sprite");
}).call(this);
