// Generated by LiveScript 1.4.0
(function(){
  var Matrix, Buffer, SpriteRenderer, slice$ = [].slice;
  Matrix = require('sylvester').Matrix;
  Buffer = require('../buffer');
  module.exports = SpriteRenderer = (function(){
    SpriteRenderer.displayName = 'SpriteRenderer';
    var prototype = SpriteRenderer.prototype, constructor = SpriteRenderer;
    function SpriteRenderer(graphics){
      this.graphics = graphics;
      this.vertices = new Buffer(this.graphics, [[-0.5, -0.5, 0.0], [0.5, -0.5, 0.0], [-0.5, 0.5, 0.0], [0.5, 0.5, 0.0]]);
      this.texCoords = new Buffer(this.graphics, [[0.0, 0.0], [1.0, 0.0], [0.0, 1.0], [1.0, 1.0]]);
    }
    prototype.render = function(entity){
      var gl, sprite, scale, translate, ref$;
      gl = this.graphics.gl;
      sprite = this.graphics.game.assets.sprites[entity.sprite];
      if ((sprite != null ? sprite.texture : void 8) == null) {
        return;
      }
      this.graphics.push();
      scale = Matrix.Scale(slice$.call(entity.size).concat([1]));
      translate = Matrix.Translation(slice$.call(entity.pos).concat([0]));
      (ref$ = this.graphics).viewMatrix = ref$.viewMatrix.x(scale).x(translate);
      this.graphics.program.uniforms.uMVMatrix.setf(this.graphics.viewMatrix);
      this.graphics.program.uniforms.uColor.setf(entity.color);
      sprite.texture.bind();
      this.graphics.program.uniforms.uSampler.seti(0);
      this.graphics.program.attributes.aVertexPosition.bind(this.vertices);
      this.graphics.program.attributes.aTextureCoord.bind(this.texCoords);
      gl.drawArrays(gl.TRIANGLE_STRIP, 0, 4);
      this.graphics.pop();
    };
    return SpriteRenderer;
  }());
}).call(this);
