// Generated by LiveScript 1.4.0
(function(){
  var Input;
  module.exports = Input = (function(){
    Input.displayName = 'Input';
    var prototype = Input.prototype, constructor = Input;
    function Input(game){
      var this$ = this;
      this.game = game;
      this.mouse = [0, 0];
      this.game.canvas.addEventListener('mousemove', function(ev){
        var rect;
        rect = this$.game.canvas.getBoundingClientRect();
        this$.mouse = [(ev.clientX - rect.left) / 2, (ev.clientY - rect.top) / 2];
      });
    }
    return Input;
  }());
}).call(this);
