// Generated by LiveScript 1.4.0
(function(){
  var Attribute;
  module.exports = Attribute = (function(){
    Attribute.displayName = 'Attribute';
    var prototype = Attribute.prototype, constructor = Attribute;
    function Attribute(program, name){
      var gl;
      this.program = program;
      this.name = name;
      gl = this.program.graphics.gl;
      this.program.attributes[this.name] = this;
      this.handle = gl.getAttribLocation(this.program.handle, this.name);
      gl.enableVertexAttribArray(this.handle);
    }
    prototype.pointer = function(size, type, normalize, stride, offset){
      var gl;
      normalize == null && (normalize = false);
      stride == null && (stride = 0);
      offset == null && (offset = 0);
      gl = this.program.graphics.gl;
      gl.vertexAttribPointer(this.handle, size, type, normalize, stride, offset);
    };
    prototype.bind = function(buffer){
      buffer.bind();
      return this.pointer(buffer.pointerSize, buffer.pointerType);
    };
    return Attribute;
  }());
}).call(this);
