// Generated by LiveScript 1.4.0
(function(){
  var Uniform, Attribute, Program, slice$ = [].slice;
  Uniform = require('./uniform');
  Attribute = require('./attribute');
  module.exports = Program = (function(){
    Program.displayName = 'Program';
    var prototype = Program.prototype, constructor = Program;
    function Program(graphics){
      var shaders, gl, i$, len$, shader;
      this.graphics = graphics;
      shaders = slice$.call(arguments, 1);
      gl = this.graphics.gl;
      this.handle = gl.createProgram();
      this.uniforms = {};
      this.attributes = {};
      for (i$ = 0, len$ = shaders.length; i$ < len$; ++i$) {
        shader = shaders[i$];
        gl.attachShader(this.handle, shader.handle);
      }
      gl.linkProgram(this.handle);
      this.info = gl.getProgramInfoLog(this.handle);
      if (!gl.getProgramParameter(this.handle, gl.LINK_STATUS)) {
        throw new Error("Error linking shader program: " + this.info);
      }
    }
    prototype.use = function(){
      var gl;
      gl = this.graphics.gl;
      gl.useProgram(this.handle);
    };
    prototype.uniform = function(name){
      new Uniform(this, name);
    };
    prototype.attribute = function(name){
      new Attribute(this, name);
    };
    return Program;
  }());
}).call(this);
