// Generated by LiveScript 1.4.0
(function(){
  var Shader, split$ = ''.split;
  module.exports = Shader = (function(){
    Shader.displayName = 'Shader';
    var prototype = Shader.prototype, constructor = Shader;
    function Shader(graphics, name, src){
      var gl, ext;
      this.graphics = graphics;
      this.name = name;
      this.src = src;
      gl = this.graphics.gl;
      ext = (split$.call(name, "."))[1];
      this.type = (function(){
        switch (ext) {
        case "vs":
          return gl.VERTEX_SHADER;
        case "fs":
          return gl.FRAGMENT_SHADER;
        }
      }());
      if (this.type == null) {
        throw new Error("Unknown shader type '" + ext + "'");
      }
      this.handle = gl.createShader(this.type);
      gl.shaderSource(this.handle, this.src);
      gl.compileShader(this.handle);
      this.info = gl.getShaderInfoLog(this.handle);
      if (!gl.getShaderParameter(this.handle, gl.COMPILE_STATUS)) {
        throw new Error("Error compiling shader '" + this.name + "': " + this.info);
      }
    }
    return Shader;
  }());
}).call(this);
