// Generated by LiveScript 1.4.0
(function(){
  var Texture;
  module.exports = Texture = (function(){
    Texture.displayName = 'Texture';
    var prototype = Texture.prototype, constructor = Texture;
    function Texture(graphics, image){
      var gl;
      this.graphics = graphics;
      this.image = image;
      gl = this.graphics.gl;
      this.handle = gl.createTexture();
      this.bind();
      gl.texImage2D(gl.TEXTURE_2D, 0, gl.RGBA, gl.RGBA, gl.UNSIGNED_BYTE, image);
      gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MAG_FILTER, gl.NEAREST);
      gl.texParameteri(gl.TEXTURE_2D, gl.TEXTURE_MIN_FILTER, gl.LINEAR_MIPMAP_NEAREST);
      gl.generateMipmap(gl.TEXTURE_2D);
      this.unbind();
    }
    prototype.bind = function(){
      var gl;
      gl = this.graphics.gl;
      gl.bindTexture(gl.TEXTURE_2D, this.handle);
    };
    prototype.unbind = function(){
      var gl;
      gl = this.graphics.gl;
      gl.bindTexture(gl.TEXTURE_2D, null);
    };
    return Texture;
  }());
}).call(this);
